	name: Hank Quinlan, Horrible Cop
	markdown: kramdown
	permalink: /blog/:year/:month/:day/:title



navigation:
  - about: /about/
  - blog: /blog/
  - cv: /cv/

baseurl: "/sydn-b.github.io"   # Add this line if you're using a subdirectory for GitHub Pages
url: "https://sydn-b.github.io"

